### ISSUE TITLE
Update library

### ISSUE THREAD

**Issue by matthewwwz** [trash-and-fire/svelte-lightweight-charts#11]
Hello, nice package! If you update lightweight-charts to 3.8.0 yourself, will nothing break?

**Comment by matthewwwz** [comment]
Can you please tell me how to update the lightweight charts library in your package?

**Comment by trash-and-fire** [comment]
Hi, you can just install 3.8.0 using `npm install light-charts@3.8.0` or any other version. This should work as there are no breaking changes in minor releases. If something goes wrong, feel free to post a question.

I haven't yet released a new version of svelte-lightweight-charts with support for the new series type (baseline). It's already in the master branch, but I want to fix a little bug with the refs.

**Comment by matthewwwz** [comment]
Thanks for the help! I'm still studying your package, before that I tried to implement it myself, but there was a problem with the ref of the Chart object and and child Series.

**Comment by trash-and-fire** [comment]
I released 1.2.0 version with support for the `<BaselineSeries>` component.
