### ISSUE TITLE
Right price scale when changing the symbol

### ISSUE THREAD

**Issue by matthewwwz** [trash-and-fire/svelte-lightweight-charts#15]
There is a problem with updating the right price scale when changing the symbol.
The new data moves to another price and the screen goes blank.
But the problem only occurs when dragging the right scale up or down with the left mouse button.
Maybe I'm doing something wrong..

So far I solved the problem through autoScale: true

`chartApi.applyOptions({
	priceScale: {
		autoScale: true
	}
})`

**Comment by matthewwwz** [comment]
![svelte-charts](https://user-images.githubusercontent.com/24637714/163601248-4b39a25b-36d9-415d-9684-7d0b1aeb0ba1.gif)

**Comment by trash-and-fire** [comment]
I believe this is the correct behaviour. Autoscale means autoscale) Without the autoscale option, the price scale remains the same as on the previous symbol, but the spread of the new symbol is much lower, so it is collapsed into a line. Also, the values of another ticker are much lower than the previous one.

**Comment by trash-and-fire** [comment]
You can also use `chartApi.priceScale().fitContent()` to auto scale on demand

**Comment by matthewwwz** [comment]
That is, after updating the ticker, it is normal behavior to use?
`chartApi.applyOptions({ priceScale: { autoScale: true } })`

**Comment by trash-and-fire** [comment]
This option will automatically scale your chart all the time. This is not a one-time scaling. Maybe you can apply this option right after the series mount and see if it suits you or not. If not, then try to turn on and immediately turn off.

Generally speaking, this discussion is outside the scope of my package. This is more about the base lightwieght-chart package. You can ask the maintainers in their repository, or ask about the scaling on demand feature.

**Comment by Newtoniano** [comment]
For reference, if anyone is running into the same problem shown in the gif, where after manually scaling the right price scale, when the price data changes (ie. new symbol data with a very different price range), it won't autoscale it, I solved this by calling `chartApi.priceScale('right').applyOptions({ autoScale: true });` after the price data changes. `priceScale()` alone without specifying `left` or `right` won't work. See [Getting reference to lightweight-chart objects](https://github.com/trash-and-fire/svelte-lightweight-charts?tab=readme-ov-file#getting-reference-to-lightweight-chart-objects) in the readme for getting the `chartApi` reference for the chart.
