### ISSUE TITLE
Component props are not reactive

### ISSUE THREAD

**Issue by matthewwwz** [trash-and-fire/svelte-lightweight-charts#17]
Component props are not reactive, passing reactive data to the Chart component's options and data to the CandlestickSeries data.

I get reactivity using the API directly, for data apply setData, and for options applyOptions, the watermark property could not also be made reactive to change the watermark

The logic is such that I get data via API and use select to change the data in the series component (props Chart, data CandlestickSeries, props CandlestickSeries)

**Comment by matthewwwz** [comment]
Maybe I'm not using your package correctly...

**Comment by trash-and-fire** [comment]
Currently only "data" should not be reactive. The rest of the properties must be reactive, I will check that again. I'll consider making the `data` prop reactive, but I made it intentionally non-reactive.

**Comment by trash-and-fire** [comment]
https://svelte.dev/repl/e01c51fc09b94d26bd515d01c69ac5f2?version=3.47.0 - There is an example with reactivity. Could you give a reproduction for non-reactive props other than `data`.

**Comment by matthewwwz** [comment]
Thanks for the quick response, it turns out that only through the $: operator is reactivity possible other than data?

**Comment by trash-and-fire** [comment]
Not only through $. It should work with any allowed reactivity in svelte: external props (export let), event handlers, and through the $ sign.

Quick example of color picker for series: https://svelte.dev/repl/dd53beb306ee45d0814562d27df2ff18

**Comment by matthewwwz** [comment]
Thanks for the example, figured out how to use reactive props. And what to do with data? Is it possible to make an additional parameter (true or false) for it to be reactive so as not to use the lightweight api directly to replace the data?

**Comment by trash-and-fire** [comment]
> Is it possible to make an additional parameter (true or false) for it to be reactive so as not to use the lightweight api directly to replace the data?

Yes, it's possible, and that's what I'm thinking about right now. But this can lead to performance issues because I have to remember the previous data and compare it with the next one. If I compare by reference, it may cause unexpected setData calls with the same data structure. If I compare by deep equality it will definitely cause huge lags. I'll test it a bit and make a decision tomorrow.

**Comment by matthewwwz** [comment]
Is it possible to give you telegrams for communication in order to throw ideas for a package or ask some simple questions?

**Comment by trash-and-fire** [comment]
I would like to stay incognito for a while) Discussions in the repository makes it more alive and maybe other members will stumble upon it on Google.

**Comment by matthewwwz** [comment]
ok, just don't drop this package, it's the only one)

**Comment by trash-and-fire** [comment]
I published [1.4.0](https://github.com/trash-and-fire/svelte-lightweight-charts/releases/tag/1.4.0) with a `reactive` property for each series type. This makes the `data` property reactive.

The "Infinite History" example is now available on the [demo page](https://trash-and-fire.github.io/svelte-lightweight-charts/official-samples.html) and [REPL](https://svelte.dev/repl/0efb2840a9844ed5a1d84f2a1c9a2269).

This example is slightly simplified using the new `<TimeScale>` component.

**Comment by matthewwwz** [comment]
Man, you are the best! I will definitely check the updates, I managed to make a lazy load historical data) thank you

**Comment by matthewwwz** [comment]
Installed, everything started right away, updated TimeScale and data became reactive, very cool
