### ISSUE TITLE
Height of histogram series

### ISSUE THREAD

**Issue by matthewwwz** [trash-and-fire/svelte-lightweight-charts#29]
Hi, how do I control the height of histogram series in overlay mode? scaleMargins doesn't help... Didn't find an answer on stackoverflow and issues lightweight-charts.

When scrolling, it happens that the height of the histogram series overlaps the candlestick series. Is it possible to control this? For example, specify height: 20% for histogram series.

Histogram series options:
`{
    color: '#385263',
    lineWidth: 2,
    priceFormat: {
      type: 'volume'
    },
    overlay: true,
    scaleMargins: {
      top: 0.90,
      bottom: 0
    }    
  }`

![chart](https://user-images.githubusercontent.com/24637714/168029363-87fad035-b64d-4455-9986-dc2d782115fa.gif)

**Comment by trash-and-fire** [comment]
Could you provide a minimal reproduction of this case. I tried to reproduce this problem on [this example](https://svelte.dev/repl/6f9de77896fe411da3ac7015f3605bb5) but everything is fine. Maybe you can change the example with your set of options and data.

**Comment by matthewwwz** [comment]
Reworked your [example](https://svelte.dev/repl/4bbf659d2404441aacdcdec74c5e3586?version=3.48.0) with real BTCUSDT data

**Comment by trash-and-fire** [comment]
Thanks, there is definitely a problem here.

**Comment by matthewwwz** [comment]
> Thanks, there is definitely a problem here.

Maybe because of the large interval between volume sizes?

**Comment by trash-and-fire** [comment]
It seems someone has already reported a similar problem https://github.com/tradingview/lightweight-charts/issues/617

**Comment by matthewwwz** [comment]
> I don't know. It can be reproduced even in the vanilla example https://jsfiddle.net/or5g63bq/. I think this is a bug in the lightweight chart

yes, thanks for the feedback!

**Comment by matthewwwz** [comment]
> You should convert values from strings into numbers. It helps.

parseFloat() will help? won't it round the value?

**Comment by matthewwwz** [comment]
> `Number("260.140")` -> `260.14`

Thanks for the help!
