### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by matthewwwz** [trash-and-fire/svelte-lightweight-charts#30]
When npm run dev and hot updates, a warning about "Circular dependency" appears in the log.

Started appearing after the last update of your package.

![log](https://user-images.githubusercontent.com/24637714/168137818-fe013a9b-5240-47a0-9a5c-68e3070ce653.png)

**Comment by trash-and-fire** [comment]
Thank you. I will fix this asap.

**Comment by trash-and-fire** [comment]
Should be fixed in [1.6.3](https://github.com/trash-and-fire/svelte-lightweight-charts/releases/tag/1.6.3)

**Comment by matthewwwz** [comment]
> Should be fixed in [1.6.3](https://github.com/trash-and-fire/svelte-lightweight-charts/releases/tag/1.6.3)

Everything is great, thanks man!
