### ISSUE TITLE
onDestroy and onMounted in series component

### ISSUE THREAD

**Issue by matthewwwz** [trash-and-fire/svelte-lightweight-charts#32]
How to catch onDestroy and onMounted event in series component? This is necessary in order to kill a websocket connection or, for example, markers in current series.

**Comment by trash-and-fire** [comment]
You can use the `ref` property. The callback is called with `ISeriesApi` when the series is available, and called with `null` when the series is destroyed.

The usage can be the same as applying ResizeObserver to the chart container. The watcher must also be destroyed on unmount, much like creating/deleting a websocket connection.

Be careful with `ref` property reference equality. If you change the callback, then the previous one will be called with null value. It behaves like a React ref-callback.

**Comment by trash-and-fire** [comment]
You can also write your own `<ConnectedSeriesComponent>` where you can use `onMount`, `onDestroy` hooks and render a regular `<[Type]Series Component>`. This case should work.

```
<Chart>
    <ConnectedSeriesComponent {ticker}/>
</Chart>
```

**Comment by matthewwwz** [comment]
Thanks for the answer! My code began to grow and I still don’t understand how to make use functions to be taken out outside of the components. Svelte does not make it possible to work with state without components.

**Comment by trash-and-fire** [comment]
Unfortunately, in my opinion, Svelte is not a well designed framework in many ways. For example, you can't extract logic containing `$` labels into a separate module. It is very uncomfortable.

To manage state outside of components, you can use [stores](https://svelte.dev/tutorial/writable-stores). You can see their API [here](https://svelte.dev/docs#run-time-svelte-store). I googled a few stores specifically for [websocket](https://www.npmjs.com/package/svelte-websocket-store) but can't say anything about their quality.

You can also try writing your own hooks like I did [this](https://github.com/trash-and-fire/svelte-lightweight-charts/blob/master/src/package/components/area-series.svelte#L100) in this [repository](https://github.com/trash-and-fire/svelte-lightweight-charts/blob/master/src/package/components/internal/utils.ts).

**Comment by matthewwwz** [comment]
> К сожалению, на мой взгляд, Svelte во многих отношениях не является хорошо спроектированным фреймворком. Например, вы не можете выделить логику, содержащую `$`метки, в отдельный модуль. Это очень неудобно.
> 
> Для управления состоянием вне компонентов можно использовать [хранилища](https://svelte.dev/tutorial/writable-stores) . Посмотреть их API можно [здесь](https://svelte.dev/docs#run-time-svelte-store) . Я погуглил несколько магазинов специально для [websocket,](https://www.npmjs.com/package/svelte-websocket-store) но ничего не могу сказать об их качестве.
> 
> Вы также можете попробовать написать свои собственные хуки, как это сделал я [в](https://github.com/trash-and-fire/svelte-lightweight-charts/blob/master/src/package/components/area-series.svelte#L100) этом [репозитории](https://github.com/trash-and-fire/svelte-lightweight-charts/blob/master/src/package/components/internal/utils.ts) .

Thanks for the info, I'll try

**Comment by matthewwwz** [comment]
Do you think Sveltekit is better designed? There is routing, adapters, and so on. I'm just looking in the direction of application scaling. Before that, I looked at Vue 3, but there everything was divided into 2 different APIs and the devil understand what is happening)

**Comment by trash-and-fire** [comment]
SvelteKit is built on top of Svelte. It's like next.js for react and nuxt for vue. It does not solve the fundamental problems of Svelte. Each framework has its pros and cons. If you've already invested your time in Svelte, perhaps you should continue instead of learning something completely new to you. Most of the problems with Svelte are more related only to the developers experience. Many technical issues have already been fixed or have workarounds.

**Comment by matthewwwz** [comment]
> SvelteKit is built on top of Svelte. It's like next.js for react and nuxt for vue. It does not solve the fundamental problems of Svelte. Each framework has its pros and cons. If you've already invested your time in Svelte, perhaps you should continue instead of learning something completely new to you. Most of the problems with Svelte are more related only to the developers experience. Many technical issues have already been fixed or have workarounds.

Thanks for the extended answer, I try to expand my knowledge, but I feel that there is still not enough experience, but this is solvable)
