### ISSUE TITLE
Sveltekit

### ISSUE THREAD

**Issue by matthewwwz** [trash-and-fire/svelte-lightweight-charts#35]
Will the package work on Sveltekit? Or is it better to wait for the 4.0 version of lightweight-charts?

**Comment by trash-and-fire** [comment]
Works only on the client side without prerendering and SSR. It cannot be imported into the nodejs environment until 4.0 is released. I think you can easily adjust this behavior for particular pages. I was able to run it here https://github.com/trash-and-fire/svelte-lightweight-charts/issues/10#issuecomment-1089064228

**Comment by trash-and-fire** [comment]
4.0 brings some breaking changes, so I will also release 2.0 with some breaking changes. I will remove the chart action and redundant code for it. The package should be much lighter.

Another reason I don't really like svelte is marketing. Not lighter bundle and not easier to develop:
https://bundlephobia.com/package/svelte-lightweight-charts@1.6.2 - svelte wrapper
https://bundlephobia.com/package/lightweight-charts-react-wrapper@1.2.0 - react wrapper

**Comment by matthewwwz** [comment]
> Работает только на стороне клиента без пререндеринга и SSR. Его нельзя импортировать в среду nodejs, пока не будет выпущена версия 4.0. Я думаю, вы можете легко настроить это поведение для конкретных страниц. Я смог запустить его здесь [# 10 (комментарий)](https://github.com/trash-and-fire/svelte-lightweight-charts/issues/10#issuecomment-1089064228)

Thank you for the detailed answer!

**Comment by matthewwwz** [comment]
> 4.0 brings some breaking changes, so I will also release 2.0 with some breaking changes. I will remove the chart action and redundant code for it. The package should be much lighter.
> 
> Another reason I don't really like svelte is marketing. Not lighter bundle and not easier to develop: https://bundlephobia.com/package/svelte-lightweight-charts@1.6.2 - svelte wrapper https://bundlephobia.com/package/lightweight-charts-react-wrapper@1.2.0 - react wrapper

Very cool done in React, I think you would increase the reach of the audience if you released a package for Vue 3

**Comment by trash-and-fire** [comment]
You can use [`svelte-lightweight-charts@2.0.0`](https://github.com/trash-and-fire/svelte-lightweight-charts/releases/tag/2.0.0)
