### ISSUE TITLE
Series Markers?

### ISSUE THREAD

**Issue by mgarsteck** [trash-and-fire/svelte-lightweight-charts#39]
How do you implement Series Markers?

**Comment by trash-and-fire** [comment]
I forgot about them. You can use `ref` and `ISeriesApi<T>::setMarkers` as a workaround. I will create a declarative API for them.

https://svelte.dev/repl/23d6219e055943a89f55c33ab61063b5

**Comment by mgarsteck** [comment]
This is very helpful thank you :)

**Comment by trash-and-fire** [comment]
Implemented in [2.1.0](https://github.com/trash-and-fire/svelte-lightweight-charts/releases/tag/2.1.0)
