### ISSUE TITLE
Draw line segments over the chart ?

### ISSUE THREAD

**Issue by Air16** [trash-and-fire/svelte-lightweight-charts#40]
Hi,

Congrats for your work !

I'm starting a project to to review trades, so I need to be able to draw line segments (entry -> exit) over a chart at specific points. 

TV Lightweight-charts would to be perfect for this, except that it does not offer this feature and the only way is to use their heavy "technical analysis chart" lib for this.

I know it is possible to add buy/sell markers, but i really need line segments over the chart.

I'm currently choosing a charting lib and I'd like to be sure it is possible before setting up the whole project.

Do you think it is possible and not so difficult using Svelte & the dom ?

Thank you

**Comment by trash-and-fire** [comment]
I'm limited to what the original library provides. It does not have drawing tools like on the trading terminal. 

You can emulate line segments using a two-point line series, but this will not allow the user to edit the line. 

A complete drawing tool will require a lot of additional code to draw moving anchors, communicate with the chart's coordinate space, hit test, and control the selection. Thus, it is easier to ask to add this feature out of the box to the core library.

**Comment by trash-and-fire** [comment]
Unfortunately, all such [requests](https://github.com/tradingview/lightweight-charts/issues?q=is%3Aissue+sort%3Aupdated-desc+drawings+is%3Aclosed+) are marked as "out of scope".

**Comment by Air16** [comment]
alright, thanks !

**Comment by trash-and-fire** [comment]
In fact, I know examples of implementing such functionality on top of the base library, but this requires a complete fork and change in the code of the base library. I don't know if the modified code is publicly available.

**Comment by Swoorup** [comment]
There is also https://github.com/liihuu/KLineChart but its in js, which might seem more flexible than lightweight chart.

**Comment by trash-and-fire** [comment]
Yeah, looks very useful.

**Comment by Air16** [comment]
> There is also https://github.com/liihuu/KLineChart but its in js, which might seem more flexible than lightweight chart.

yes just found it, looks very promising. Probably the right guy for me. Thanks
