### ISSUE TITLE
Multiples panels

### ISSUE THREAD

**Issue by MuslemRahimi** [trash-and-fire/svelte-lightweight-charts#41]
Hi I want to share the x-axis with multiple panels where the y-axis can be different. 

Here is a simple example of what i mean: https://jsfiddle.net/h0wXD/g75Lmady/

Is there a way to do this in svelte? If yes can you provide a simple example to me.

**Comment by trash-and-fire** [comment]
Yes it is possible.

```
<div id="chart" on:mousemove={handleChartContainerMouseMove}>
    <Chart on:crosshairMove={handleChartCrosshairMove}>
        <BarSeries/>
        <TimeScale on:visibleLogicalRangeChange={syncWithAxis}/>
    </Chart>
</div>
<div id="axis" on:mousemove={handleAxisContainerMouseMove}>
    <Chart on:crosshairMove={handleAxisCrosshairMove}>
        <LineSeries/>
        <TimeScale on:visibleLogicalRangeChange={syncWithChart}/>
    </Chart>
</div>
```

**Comment by trash-and-fire** [comment]
Example of event handler:
```
<TimeScale on:visibleLogicalRangeChange={(e) => axis.timeScale().setVisibleLogicalRange(e.detail)}/>
```

**Comment by trash-and-fire** [comment]
Your request is quite interesting, I will add the full implementation to the gallery of examples a bit later.

**Comment by MuslemRahimi** [comment]
thanks for the solution. Please keep up the updates. The repo is really good

**Comment by trash-and-fire** [comment]
Try the [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) tag or [conditional rendering](https://svelte.dev/tutorial/if-blocks).

**Comment by MuslemRahimi** [comment]
> Yes it is possible.
> 
> ```
> <div id="chart" on:mousemove={handleChartContainerMouseMove}>
>     <Chart on:crosshairMove={handleChartCrosshairMove} ref={(ref) => chart = ref}>
>         <BarSeries/>
>         <TimeScale on:visibleLogicalRangeChange={syncWithAxis}/>
>     </Chart>
> </div>
> <div id="axis" on:mousemove={handleAxisContainerMouseMove}>
>     <Chart on:crosshairMove={handleAxisCrosshairMove} ref={(ref) => axis = ref}>
>         <LineSeries/>
>         <TimeScale on:visibleLogicalRangeChange={syncWithChart}/>
>     </Chart>
> </div>
> ```

Can you provide a full simple example of how to use it. Since i dont know how syncwithCart, handleAxisCrosshairMove etc are defined

**Comment by trash-and-fire** [comment]
Your fiddle uses an unofficial fork of `lightweight-charts` with the `moveCrosshair` extension method. You can provide it to `svelte-lightweight-charts` via a bundler alias or a package manager alias.

I can only give an [example](https://svelte.dev/repl/9175d726c7a24c39a855f0a50547d968?version=3.55.0) of charts with synchronized scroll.

**Comment by MuslemRahimi** [comment]
Just for the record. If you have more than two graphs (e.g. Chart, RSI and MACD) and you want them sync then you have to modify the above code in the following way:

`
    let axisRSI;
    let axisMACD;
    let chart;
    
    const handleChartLogicalRangeChange = (e) => {
        const range = e.detail;
        try
        { 
        axisRSI.timeScale().setVisibleLogicalRange(range);
        }
        catch(error) {
          //pass;
        }

        try
        { 
        axisMACD.timeScale().setVisibleLogicalRange(range);
        }
        catch(error) {
          //pass;
        }
    }

    const handleAxisLogicalRangeChange = (e) => {
        const range = e.detail;
        chart.timeScale().setVisibleLogicalRange(range)
    }`
