### ISSUE TITLE
Constrain scrolling to future data that does not exist

### ISSUE THREAD

**Issue by MuslemRahimi** [trash-and-fire/svelte-lightweight-charts#42]
What should i do when i don't want to see future data that does not exist yet. 

Below i have an example

![image](https://user-images.githubusercontent.com/22890183/210604720-b21a22b0-e836-4656-a1b9-06b66756b25a.png)

I dont want the user to scroll forward in time when there is no data. Is there a simple way to constrain that?

**Comment by trash-and-fire** [comment]
You can use [`fixRightEdge`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#fixrightedge) option.

```
<TimeScale fixRightEdge={true}/>
```

**Comment by trash-and-fire** [comment]
Combined with [`rightOffset`](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/TimeScaleOptions#rightoffset) you can get a fixed offset to the right after the most recent candle.
