### ISSUE TITLE
fill between two prices

### ISSUE THREAD

**Issue by MuslemRahimi** [trash-and-fire/svelte-lightweight-charts#44]
Is it possible to fill the area between two prices. Here is an example of what i am looking for.

![grafik](https://user-images.githubusercontent.com/22890183/211211203-97e65df7-77c0-45eb-a7c1-b655fbfc6865.png)

I would appreciate it alot if you can help me out on this

**Comment by trash-and-fire** [comment]
As far as I know this is not possible with the basic version of the lightweight-charts package.

**Comment by MuslemRahimi** [comment]
is there no way to overcome this... Maybe playing around with AreaSeries

**Comment by trash-and-fire** [comment]
I don't think so. AreaSeries accept [SingleValueData](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SingleValueData) which contains only one value. As I see in your picture, you need to provide at least two values for each time point and fill in the space between them.

https://github.com/tradingview/lightweight-charts/issues/140
