### ISSUE TITLE
Possible nodejs version incompatability?

### ISSUE THREAD

**Issue by ihostuplay** [trash-and-fire/svelte-lightweight-charts#6]
Usage:
import chart from "svelte-lightweight-charts";
^ within my App.svelte running nodejs version 14.17.6

Error:
'default' is not exported by node_modules\svelte-lightweight-charts\index.js

Possible fix:
I just added 'default' on line 3 within 'svelte-lightweight-charts\index.js' like this:
'export default function chart(node, params) {'
and it removed the error

Other:
Love the repo! It's sooooo handy... Thx a lot.

**Comment by trash-and-fire** [comment]
Thank you for your message.

In order not to break possible use cases `import {chart} from 'svelte-lightweight-charts'` I added an additional default export of the same function as per the sample in the documentation. It is available in 1.1.1

Feel free to write an additional feedback.
