### ISSUE TITLE
I want to optionally apply rightPriceScale in LineSeries 

### ISSUE THREAD

**Issue by Elliott-Green** [trash-and-fire/svelte-lightweight-charts#63]
Hi, cool library! 

I'm using a Line series like
```ts
	<Chart {...chartOptions}>
		{#each graphData as d}
			<LineSeries data={d} reactive={true} />
		{/each}
	</Chart>
```

I have a series of data which might have gaps. Reading from https://github.com/tradingview/lightweight-charts/issues/699 there's not any offical support for this apart from 'create a new series' to create the gap effect. 

I've created a custom mapping which does this logic of splitting gaps into a new series (leaving them all in the same series, draws a single line through points which don't have a value), this now allows me gaps in my charts! 

![image](https://user-images.githubusercontent.com/10979087/219163768-649069c3-61dd-4c14-9100-2f2fd6db2088.png)

The issue I've been trying to solve since is removing the rightPriceScale for the older series, I only want to show the priceLine for the most recent series. I can write a map function so I have that bool visible in the variable `graphData as d`.

I've been just playing around with adding extra options to LineSeries - `priceLineVisible`, `priceScaleId` and the other visible options, all but `visible` cause no effect on the rightPriceScale, and `visible` isn't what I want anyways. But it seems like I can remove them by setting

```ts
  rightPriceScale: {
    visible: true
  }
```

Is there a way to optionally apply this during the foreach?

I've seen similar code doing logic like

```ts
splitUpSeriesWithGaps(originalSeries).forEach((series) => {
    const lineSeries = chart.addLineSeries({
        lineStyle: 2,
        priceLineVisible: false,
    });
    lineSeries.setData(series);
});
```
Thanks!

**Comment by trash-and-fire** [comment]
If I understand correctly you can use `lastValueVisible` and `priceLineVisible` props on a series to control price line and value on the price scale.

https://svelte.dev/repl/443579ea37164a368c91ea0e79c390b0?version=3.55.1

**Comment by Elliott-Green** [comment]
Thank you!
![image](https://user-images.githubusercontent.com/10979087/219219627-30c62b28-dbdb-48f8-a21b-72bdde622e33.png)

Another question I have, is that I can render different timeframe of charts (7d, 30d, all-time). 

When loading the all-time on-mount, it will scale perfectly - when I change to 7d and back to all-time, my chart isn't resizing properly 

I've tried setting, but it has no effect 

```ts
		timeScale: {
			from: graphData[0][0],
			to: graphData[0][graphData[0].length - 1]
		},
```

Would you know what function or property I can set for this?

**Comment by trash-and-fire** [comment]
https://svelte.dev/repl/1546200259d145aa8c48c5ca25b4a586?version=3.55.1 you can manage visible time range using `setVisibleTimeRange` on `ITimeScaleApi`

**Comment by Elliott-Green** [comment]
Thank you!

I managed to solve this by adding `ref={(ref) => chartApi = ref}` to my chart, giving me access to the API and then on afterUpdate calling `chartApi.timeScale().fitContent()` will work.
