### ISSUE TITLE
Better UX for Mobile Device

### ISSUE THREAD

**Issue by MuslemRahimi** [trash-and-fire/svelte-lightweight-charts#67]
Hi,

I wanted to have your opinion about my svelte-lightweight-chart in my website: https://stocknear.com/

In my opinion, the vertical that outputs the Price in the legend is still a little unstable ( dont feel good or smooth).
That's because I have to hold my finger down for 1-2 seconds before the vertical line appears.
Is there a way to make it happen instantly when the user swipes left or right but not appear when the user swipes up or down?

My options have the settings:
```
const options = {
  layout: {
    backgroundColor: '#1A1A27',
    textColor: '#FFFFFF',
  },
  grid: {
    vertLines: {
      color: '#1A1A27',
      visible: false,
    },
    horzLines: {
      color: '#1A1A27',
      visible: false,
    },
  },
  crosshair: {
    // hide the horizontal crosshair line
    horzLine: {
      visible: false,
      labelVisible: false,
    },
    // hide the vertical crosshair label
    vertLine: {
      labelVisible: false,
      style: 0,
    },
  },
  rightPriceScale: {
    visible: false,
    borderColor: 'rgba(197, 203, 206, 0.8)',
  },
  handleScale: {
    mouseWheel: false,
  },
  handleScroll: {
    mouseWheel: false,
    horzTouchDrag: false,
    vertTouchDrag: false,
    pressedMouseMove: false,
  },
  
  timeScale: {
    borderColor: '#FFFFFF',
    textColor: '#FFFFFF',
    visible: false,
    fixLeftEdge: true,
    fixRightEdge: true,
  },
  
};

```

I would appreciate alot your help. Please open the site with your smartphone. 
(PS: If you have a iphone the site will first crash because top-level await is not supported in safari 14 :-1: ) 
All you need to do is go back to Homepage and click on a stock ticker such as Google and it will work again :)

**Comment by trash-and-fire** [comment]
> Is there a way to make it happen instantly when the user swipes left or right but not appear when the user swipes up or down?
I am not sure that it is possible to predict when a user wants to swipe right or down. Also I don't know options to remove or customize a delay for entering into the tracking mode.

The only thing you can customize: `trackingMode: { exitMode: TrackingModeExitMode.onTouchEnd }`

https://tradingview.github.io/lightweight-charts/docs/api/enums/TrackingModeExitMode#ontouchend

**Comment by MuslemRahimi** [comment]
thanks for your feedback. Im trying to add ```
const options = {
...
trackingMode: {
	exitMode: TrackingModeExitMode.OnTouchEnd,
},
...
```
I get the error that TrackingModeExitMode is not defined. i tried loading it with ```import {TrackingModeExitMode} from 'lightweight-charts';
```

**Comment by trash-and-fire** [comment]
`TrackingModeExitMode` should be defined in `lighweight-charts` package. But it seems like I did not support this property in `svelte-lightweight-charts`.
```
"<Chart> was created with unknown prop 'trackingMode'"
```

I will do it in 2.1.0

**Comment by MuslemRahimi** [comment]
> `TrackingModeExitMode` should be defined in `lightweight-charts` package. But it seems like I did not support this property in `svelte-lightweight-charts`.
> 
> ```
> "<Chart> was created with unknown prop 'trackingMode'"
> ```
> 
> I will do it in 2.1.0


Ive upgraded my lightweight-charts to version 4.0 but still the code with:
...
trackingMode: {
	exitMode: TrackingModeExitMode.OnTouchEnd,
},
...
doe not work. Can you provide a example to demonstrate that the vertical line disappears after the user dont touch the graph anymore

**Comment by trash-and-fire** [comment]
https://svelte.dev/repl/3000c58829f44adaa4bdd40044748ef9?version=3.55.1 as workaround to apply this option
