### ISSUE TITLE
Does Lineseries and Candlestick  only work with 'yyyy-mm-dd'?

### ISSUE THREAD

**Issue by mgarsteck** [trash-and-fire/svelte-lightweight-charts#68]
When making a chart that is under the daily timeframe, I am returned an error.  It appears that the only allowed date format is yyyy-mm-dd instead of yyyy-mm-dd-hh-mm-ss.  I need my chart to be able to read data with timeframes under the daily. I dont know why this would be the case.
[repl](https://svelte.dev/repl/cd4e48df37624441b9467000bc5014f3?version=3.55.1)

**Comment by trash-and-fire** [comment]
You can use UTCTimestamp instead of string. https://tradingview.github.io/lightweight-charts/docs/api#utctimestamp

> If your chart displays an intraday interval you should use a UNIX Timestamp.
Note that JavaScript Date APIs like Date.now return a number of milliseconds but UTCTimestamp expects a number of seconds.

**Comment by mgarsteck** [comment]
I am not able to import that module from lwc. I have converted to UTC and the lineseries plots out of order even though my array is sorted by date

**Comment by mgarsteck** [comment]
I tried that example but get an error that UTCTimestamp is not exported by LWC.  Is it not simply taking millisecond time and dividing it by 1000?

**Comment by trash-and-fire** [comment]
You don't need to import UTCTimestamp from LWC. UTCTimestamp is just a plain number with certain condition - the number of seconds since January 1st, 1970. Just use numbers like 1529899200.

**Comment by mgarsteck** [comment]
right, so milliseconds / 1000 should give me the appropriate result correct?

**Comment by trash-and-fire** [comment]
Yes. Right. Just use milliseconds divided by 1000.

**Comment by mgarsteck** [comment]
Ok good, thats what I did.  It works on daily and weekly (which is great), but when you go intra-day, I get 'Uncaught error value is null' but there is no null values in my data and its on the the same date format.

**Comment by trash-and-fire** [comment]
I can't help you without reproduction of the error. Make sure your data is consistent over time and and ordered chronologically
