### ISSUE TITLE
Vertical Price Line

### ISSUE THREAD

**Issue by MuslemRahimi** [trash-and-fire/svelte-lightweight-charts#69]
Is there a way to plot a vertical PriceLine similar to 
```
<PriceLine
      price={filteredData.threeYearsAgo[0].value}
      lineWidth = {1.5}
      color="#d4d9d9"
    />
```

for a specific date let say "2023-02-02"?

**Comment by trash-and-fire** [comment]
Short answer is NO. Unfortunately it is not supported by LWC. Long answer you can find here https://github.com/tradingview/lightweight-charts/issues?q=is%3Aissue+vertical+line+is%3Aclosed .

**Comment by MuslemRahimi** [comment]
With the newest version of lightweight-charts 4.10 it is possible to add a vertical line:
https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/vertical-line/example/

Can you add the feature to your library please

**Comment by trash-and-fire** [comment]
https://github.com/trash-and-fire/svelte-lightweight-charts/issues/82#issuecomment-1763361593 Vertical Lines.
