### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MuslemRahimi** [trash-and-fire/svelte-lightweight-charts#77]
Hi,

Is it possible to add the feature that the last value of a lineseries is pulsing, see https://tradingview.github.io/lightweight-charts/docs/api/enums/LastPriceAnimationMode. 

Would appreciate it alot.

Thanks

**Comment by trash-and-fire** [comment]
Yes. It is possible. It will be added in 2.2.0. Thanks for this find.

**Comment by MuslemRahimi** [comment]
In the meantime, how can i add the animation. At the moment i have:
`
const options = {
  layout: {
    background: {
      color: '#1A1A27',
    },
  
  },
  grid: {
    vertLines: {
      color: '#1A1A27',
      visible: false,
    },
    horzLines: {
      color: '#1A1A27',
      visible: false,
    },
  },
  crosshair: {
    // hide the horizontal crosshair line
    horzLine: {
      visible: false,
      labelVisible: false,
    },
    // hide the vertical crosshair label
    vertLine: {
      labelVisible: false,
      style: 0,
    },
  },
  rightPriceScale: {
    visible: false,
    borderColor: 'rgba(197, 203, 206, 0.8)',
  },
  leftPriceScale: {
    visible: false,
    borderColor: 'rgba(197, 203, 206, 0.8)',
  },
  handleScale: {
    mouseWheel: false,
  },
  handleScroll: {
    mouseWheel: false,
    horzTouchDrag: false,
    vertTouchDrag: false,
    pressedMouseMove: false,
  },
  timeScale: {
    borderColor: '#FFFFFF',
    textColor: '#FFFFFF',
    visible: false,
    fixLeftEdge: true,
    fixRightEdge: true,
  },
  lastPriceAnimation: LastPriceAnimationMode.OnDataUpdate,
};`

**Comment by trash-and-fire** [comment]
You can use `applyOptions` on the series ref, or wait until I publish the next version today.

**Comment by MuslemRahimi** [comment]
> You can use `applyOptions` on the series ref, or wait until I publish the next version today.

Ah nice, i will wait then

**Comment by trash-and-fire** [comment]
Done in 2.2.0
