### ISSUE TITLE
Continuous Pulse animation

### ISSUE THREAD

**Issue by MuslemRahimi** [trash-and-fire/svelte-lightweight-charts#79]
Hi,

Is it possible to add the functionality that the last value animation is showing continuously the pulse animation?

**Comment by trash-and-fire** [comment]
I guess you need to set up `lastPriceAnimation` to `1` or `LastPriceAnimationMode.Continuous`.

https://tradingview.github.io/lightweight-charts/docs/api/enums/LastPriceAnimationMode#continuous
