### ISSUE TITLE
**not an issue** feature question

### ISSUE THREAD

**Issue by nickforce** [trash-and-fire/svelte-lightweight-charts#81]
Amazing library, thank you for creating it!

Is there a way to add markers to a line chart? For example I am displaying a line chart with moving averages and want to display simple markers with text at various price points on the chart. Is this possible with the current library of components?

**Comment by trash-and-fire** [comment]
Yes. Use `markers` property. https://svelte.dev/repl/2a874b081cd9465e8eaa7ceef0d42cca?version=4.2.0

There is documentation for [SeriesMarker](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/SeriesMarker) interface.

**Comment by nickforce** [comment]
Perfect, exactly what I was looking for. Thank you! @trash-and-fire
