### ISSUE TITLE
Feature Request: Add Tracking Mode for mobile devices

### ISSUE THREAD

**Issue by MuslemRahimi** [trash-and-fire/svelte-lightweight-charts#83]
Hi,

is it possible to add the new feature of lightweight-charts 4.10 into your library?

https://github.com/tradingview/lightweight-charts/issues/1198

I would much appreciated it!

**Comment by trash-and-fire** [comment]
Yes, sure. Some of them are already planned [here](https://github.com/trash-and-fire/svelte-lightweight-charts/issues/82#issue-1860230349), but I will definitely support all new features.

**Comment by trash-and-fire** [comment]
In fact, you can use this feature right now. Just update the lwc package to version 4.10. This feature is available on the chart api ref.

https://svelte.dev/repl/423c010002ce47b89ff3682c22c5735a?version=4.2.1
