### ISSUE TITLE
Creating Minicharts

### ISSUE THREAD

**Issue by MuslemRahimi** [trash-and-fire/svelte-lightweight-charts#86]
Hi,

I want to create something similar like the picture in your library. 
Do you know if it is possible to do so?

![Screenshot from 2024-01-20 09-59-46](https://github.com/trash-and-fire/svelte-lightweight-charts/assets/22890183/132a8efa-be54-4c09-b48e-a196cebd40b9)

**Comment by trash-and-fire** [comment]
Yes it is possible. You can turn off both scales and zoom, set the correct size and colors, and then add BaseLineSeries.

**Comment by trash-and-fire** [comment]
https://svelte.dev/repl/1157da71310f44d886f384239c177a2b?version=4.2.9 I'm trying to understand why the baseline isn't showing

**Comment by MuslemRahimi** [comment]
Thanks to your code I could replicate it quite nice so far

![Screenshot from 2024-01-22 13-52-38](https://github.com/trash-and-fire/svelte-lightweight-charts/assets/22890183/664f634d-4f99-4ae3-8c52-cc869d559a55)

If the horizontal dashed line would be working too that would be great

**Comment by MuslemRahimi** [comment]
So I added the x-axis line like this now
```
<BaselineSeries
      data={priceData}
      {...theme.series}
      topLineColor ={topLineColor}
      topFillColor1 ={topFillColor1}
      bottomLineColor ={bottomLineColor}
      bottomFillColor1 ={bottomFillColor1}
      >
      <PriceLine
        price={priceData[0]?.value}
        lineWidth = {1.5}
        color="#fff"
      />
```
![Screenshot from 2024-01-22 15-05-35](https://github.com/trash-and-fire/svelte-lightweight-charts/assets/22890183/203e6615-0fdc-4525-91b7-9f0cb87ac60d)
