### ISSUE TITLE
Update chart

### ISSUE THREAD

**Issue by Kaexburli** [trash-and-fire/svelte-lightweight-charts#9]
Hi, 

how we update the chart ???

pushing new data into data variable does not work!

I test the candelstick model, I can't find a method update in Chart

Thank's

**Comment by trash-and-fire** [comment]
I've made an [example](https://svelte.dev/repl/9599a30980ee4a029b1556b6ef4e96c5?version=3.44.3) for you. It is little bit tricky.

There is no declarative API for updating data. You can get a reference for any series and call the [update](https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ISeriesApi#update) method.

You can also take a look at the [debug page](https://trash-and-fire.github.io/svelte-lightweight-charts/) (click "start") and read [the code](https://github.com/trash-and-fire/svelte-lightweight-charts/blob/master/src/demo/app.svelte) of this page

**Comment by Kaexburli** [comment]
I think it works !!!

thank you for everything

![lightweigthchart-realtime-ok](https://user-images.githubusercontent.com/67260798/147394880-b6f1d8f8-2d9d-4580-b75b-526311470853.png)
